name: FRUK Docker Image CI

on:
  push:
    paths-ignore:
      - .gitignore
      - Makefile
      - README.md

env:
  IMAGE_TAG: $(date +%s)

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker build and push
        uses: cloudposse/github-action-docker-build-push@1.13.1
        with:
          workdir: ./site
          file: Dockerfile
          registry: registry.digitalocean.com/fratcliffe
          image_name: fruk
          login: ${{ secrets.DO_REGISTRY_TOKEN }}
          password: ${{ secrets.DO_REGISTRY_TOKEN }}
          tags: ${{ env.IMAGE_TAG }}
