name: FRUK Docker Image CI

on:
  push:
    paths-ignore:
      - .gitignore
      - Makefile
      - README.md

env:
  IMAGE_TAG: $(date +%s)

jobs:
  directory:
    runs-on: ubuntu-latests
    steps:
      - name: Print github.workspace
        run: echo ${{ github.workspace }}
#   docker:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Docker Build & Push Action
#         uses: mr-smithers-excellent/docker-build-push@v6.2
#         with:
#           image: fruk
#           tags: ${{ env.IMAGE_TAG }}
#           registry: registry.digitalocean.com/fratcliffe
#           dockerfile: ../../site/Dockerfile
#           directory: ../../site
#           username: ${{ secrets.DO_REGISTRY_TOKEN }}
#           password: ${{ secrets.DO_REGISTRY_TOKEN }}
