name: FRUK Docker Image CI

on:
  push:
    paths-ignore:
      - .gitignore
      - Makefile
      - README.md

env:
  IMAGE_TAG: ${{github.ref_name}}

jobs:
  troubleshoot:
    runs-on: ubuntu-latest
    steps:
      - name: Print directory structure
        uses: FiorelaCiroku/XDTesting-Print-Directory-Structure@v1.0.2
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker build and push
        uses: cloudposse/github-action-docker-build-push@main
        with:
          workdir: ./site
          registry: registry.digitalocean.com/fratcliffe
          image_name: fruk
          login: ${{ secrets.DO_REGISTRY_TOKEN }}
          password: ${{ secrets.DO_REGISTRY_TOKEN }}
          tags: ${{ env.IMAGE_TAG }}
