name: FRUK Docker Image CI

on:
  push:
    paths-ignore:
      - .gitignore
      - Makefile
      - README.md

env:
  IMAGE_TAG: $(date +%s)

jobs:
  investigate:
    runs-on: ubuntu-latest
    steps:
      - name: Find Dockerfiles
        if: always()
        run: find ../../../../ -name Dockerfile
      - name: List .nvm
        if: always()
        run: ls -lash ../../../.nvm/
      - name: cat ../../../.nvm/
        if: always()
        run: ls -lash ../../../.nvm/Dockerfile
#   docker:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Docker Build & Push Action
#         uses: mr-smithers-excellent/docker-build-push@v6.2
#         with:
#           image: fruk
#           tags: ${{ env.IMAGE_TAG }}
#           registry: registry.digitalocean.com/fratcliffe
#           dockerfile: ../../site/Dockerfile
#           directory: ../../site
#           username: ${{ secrets.DO_REGISTRY_TOKEN }}
#           password: ${{ secrets.DO_REGISTRY_TOKEN }}
