name: FRUK Docker Image CI

on:
  push:
    paths-ignore:
      - .gitignore
      - Makefile
      - README.md

env:
  IMAGE_TAG: ${{github.ref_name}}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Docker build and push
        uses: cloudposse/github-action-docker-build-push@main
        with:
          file: ./site/Dockerfile
          registry: registry.digitalocean.com/fratcliffe
          image_name: fruk
          login: ${{ secrets.DO_REGISTRY_TOKEN }}
          password: ${{ secrets.DO_REGISTRY_TOKEN }}
          tags: type=raw,value=${{github.ref_name}}
