name: FRUK Docker Image CI

on:
  push:
    paths-ignore:
      - .gitignore
      - Makefile
      - README.md

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build FRUK Docker image
        run: docker build ./site --file ./site/Dockerfile --tag registry.digitalocean.com/fratcliffe/fruk:$(date +%s)
